import type { HostingPlan } from "@/lib/site-types";

/**
 * Fallback product catalog used when WHMCS is not configured yet
 * (USE_WHMCS_PRODUCTS=false) or unreachable.
 *
 * Once WHMCS is connected, the server tries WHMCS first (via the
 * provider layer) and this catalog is only a graceful fallback.
 * `whmcsPid` maps each plan to the real WHMCS product id.
 */
export const defaultPlans: HostingPlan[] = [
  /* ------------------------------ Web Hosting ----------------------------- */
  {
    id: "web-starter",
    category: "web",
    name: "Starter",
    tagline: "Perfect for a first website or blog.",
    whmcsPid: 1,
    billingCycles: ["monthly", "annually"],
    prices: {
      bdt: { monthly: 49, annually: 490 },
      usd: { monthly: 1.5, annually: 15 },
    },
    features: [
      "1 website",
      "10 GB NVMe storage",
      "50 GB bandwidth",
      "Free SSL",
      "Daily backups",
      "cPanel + LiteSpeed",
    ],
    resourceSpecs: [
      { label: "Storage", value: "10 GB NVMe" },
      { label: "Bandwidth", value: "50 GB" },
      { label: "Websites", value: "1" },
      { label: "Email accounts", value: "5" },
      { label: "Databases", value: "1" },
      { label: "SSL", value: "Free" },
    ],
  },
  {
    id: "web-business",
    category: "web",
    name: "Business",
    tagline: "Our most popular plan for growing sites.",
    popular: true,
    whmcsPid: 2,
    billingCycles: ["monthly", "annually"],
    prices: {
      bdt: { monthly: 99, annually: 990 },
      usd: { monthly: 3, annually: 30 },
    },
    features: [
      "Unlimited websites",
      "50 GB NVMe storage",
      "Unlimited bandwidth",
      "Free SSL",
      "Daily backups",
      "cPanel + LiteSpeed",
      "Free domain (.com)",
    ],
    resourceSpecs: [
      { label: "Storage", value: "50 GB NVMe" },
      { label: "Bandwidth", value: "Unlimited" },
      { label: "Websites", value: "Unlimited" },
      { label: "Email accounts", value: "Unlimited" },
      { label: "Databases", value: "Unlimited" },
      { label: "SSL", value: "Free" },
    ],
  },
  {
    id: "web-professional",
    category: "web",
    name: "Professional",
    tagline: "For online stores and business sites.",
    whmcsPid: 3,
    billingCycles: ["monthly", "annually"],
    prices: {
      bdt: { monthly: 199, annually: 1990 },
      usd: { monthly: 6, annually: 60 },
    },
    features: [
      "Unlimited websites",
      "100 GB NVMe storage",
      "Unlimited bandwidth",
      "Free SSL",
      "Daily backups",
      "Priority support",
      "Free domain (.com)",
    ],
    resourceSpecs: [
      { label: "Storage", value: "100 GB NVMe" },
      { label: "Bandwidth", value: "Unlimited" },
      { label: "Websites", value: "Unlimited" },
      { label: "Email accounts", value: "Unlimited" },
      { label: "Databases", value: "Unlimited" },
      { label: "SSL", value: "Free" },
    ],
  },
  {
    id: "web-enterprise",
    category: "web",
    name: "Enterprise",
    tagline: "Maximum resources for demanding projects.",
    whmcsPid: 4,
    billingCycles: ["monthly", "annually"],
    prices: {
      bdt: { monthly: 399, annually: 3990 },
      usd: { monthly: 12, annually: 120 },
    },
    features: [
      "Unlimited websites",
      "200 GB NVMe storage",
      "Unlimited bandwidth",
      "Free SSL + dedicated IP",
      "Daily backups",
      "Priority support",
      "Free domain (.com)",
    ],
    resourceSpecs: [
      { label: "Storage", value: "200 GB NVMe" },
      { label: "Bandwidth", value: "Unlimited" },
      { label: "Websites", value: "Unlimited" },
      { label: "Email accounts", value: "Unlimited" },
      { label: "Databases", value: "Unlimited" },
      { label: "SSL", value: "Free + dedicated IP" },
    ],
  },

  /* ----------------------------- BDIX Hosting ---------------------------- */
  {
    id: "bdix-basic",
    category: "bdix",
    name: "BDIX Basic",
    tagline: "Local hosting for a personal site.",
    whmcsPid: 11,
    billingCycles: ["monthly", "annually"],
    prices: {
      bdt: { monthly: 69, annually: 690 },
      usd: { monthly: 2, annually: 20 },
    },
    features: [
      "1 website",
      "15 GB NVMe storage",
      "100 GB bandwidth",
      "BDIX + international uplink",
      "Free SSL",
      "Daily backups",
    ],
    resourceSpecs: [
      { label: "Storage", value: "15 GB NVMe" },
      { label: "Bandwidth", value: "100 GB" },
      { label: "Websites", value: "1" },
      { label: "Email accounts", value: "10" },
      { label: "Databases", value: "5" },
      { label: "SSL", value: "Free" },
    ],
  },
  {
    id: "bdix-standard",
    category: "bdix",
    name: "BDIX Standard",
    tagline: "Low-latency hosting for Bangladeshi visitors.",
    popular: true,
    whmcsPid: 12,
    billingCycles: ["monthly", "annually"],
    prices: {
      bdt: { monthly: 129, annually: 1290 },
      usd: { monthly: 4, annually: 40 },
    },
    features: [
      "Unlimited websites",
      "40 GB NVMe storage",
      "Unlimited bandwidth",
      "BDIX + international uplink",
      "Free SSL",
      "Daily backups",
    ],
    resourceSpecs: [
      { label: "Storage", value: "40 GB NVMe" },
      { label: "Bandwidth", value: "Unlimited" },
      { label: "Websites", value: "Unlimited" },
      { label: "Email accounts", value: "Unlimited" },
      { label: "Databases", value: "Unlimited" },
      { label: "SSL", value: "Free" },
    ],
  },
  {
    id: "bdix-business",
    category: "bdix",
    name: "BDIX Business",
    tagline: "For businesses with high local traffic.",
    whmcsPid: 13,
    billingCycles: ["monthly", "annually"],
    prices: {
      bdt: { monthly: 249, annually: 2490 },
      usd: { monthly: 7.5, annually: 75 },
    },
    features: [
      "Unlimited websites",
      "80 GB NVMe storage",
      "Unlimited bandwidth",
      "Priority BDIX bandwidth",
      "Free SSL",
      "Daily backups + priority restore",
    ],
    resourceSpecs: [
      { label: "Storage", value: "80 GB NVMe" },
      { label: "Bandwidth", value: "Unlimited" },
      { label: "Websites", value: "Unlimited" },
      { label: "Email accounts", value: "Unlimited" },
      { label: "Databases", value: "Unlimited" },
      { label: "SSL", value: "Free" },
    ],
  },

  /* ----------------------------- Turbo Hosting ---------------------------- */
  {
    id: "turbo-start",
    category: "turbo",
    name: "Turbo Start",
    tagline: "Performance shared hosting to start.",
    whmcsPid: 21,
    billingCycles: ["monthly", "annually"],
    prices: {
      bdt: { monthly: 129, annually: 1290 },
      usd: { monthly: 4, annually: 40 },
    },
    features: [
      "1 website",
      "20 GB NVMe storage",
      "Unlimited bandwidth",
      "LiteSpeed + LSCache",
      "Free SSL",
      "Daily backups",
      "Priority CPU",
    ],
    resourceSpecs: [
      { label: "Storage", value: "20 GB NVMe" },
      { label: "Bandwidth", value: "Unlimited" },
      { label: "Websites", value: "1" },
      { label: "CPU allocation", value: "2x standard" },
      { label: "LiteSpeed", value: "Yes + LSCache" },
      { label: "SSL", value: "Free" },
    ],
  },
  {
    id: "turbo-pro",
    category: "turbo",
    name: "Turbo Pro",
    tagline: "Serious speed for serious sites.",
    popular: true,
    whmcsPid: 22,
    billingCycles: ["monthly", "annually"],
    prices: {
      bdt: { monthly: 249, annually: 2490 },
      usd: { monthly: 7.5, annually: 75 },
    },
    features: [
      "Unlimited websites",
      "60 GB NVMe storage",
      "Unlimited bandwidth",
      "LiteSpeed + LSCache",
      "Free SSL",
      "Daily backups",
      "Higher CPU & memory limits",
    ],
    resourceSpecs: [
      { label: "Storage", value: "60 GB NVMe" },
      { label: "Bandwidth", value: "Unlimited" },
      { label: "Websites", value: "Unlimited" },
      { label: "CPU allocation", value: "4x standard" },
      { label: "LiteSpeed", value: "Yes + LSCache" },
      { label: "SSL", value: "Free" },
    ],
  },
  {
    id: "turbo-max",
    category: "turbo",
    name: "Turbo Max",
    tagline: "The fastest shared hosting we offer.",
    whmcsPid: 23,
    billingCycles: ["monthly", "annually"],
    prices: {
      bdt: { monthly: 449, annually: 4490 },
      usd: { monthly: 13.5, annually: 135 },
    },
    features: [
      "Unlimited websites",
      "150 GB NVMe storage",
      "Unlimited bandwidth",
      "LiteSpeed + LSCache",
      "Free SSL + dedicated IP",
      "Advanced daily backups",
      "Maximum CPU & memory",
    ],
    resourceSpecs: [
      { label: "Storage", value: "150 GB NVMe" },
      { label: "Bandwidth", value: "Unlimited" },
      { label: "Websites", value: "Unlimited" },
      { label: "CPU allocation", value: "6x standard" },
      { label: "LiteSpeed", value: "Yes + LSCache" },
      { label: "SSL", value: "Free + dedicated IP" },
    ],
  },

  /* --------------------------- Reseller Hosting --------------------------- */
  {
    id: "reseller-silver",
    category: "reseller",
    name: "Silver",
    tagline: "Start your hosting business today.",
    whmcsPid: 31,
    billingCycles: ["monthly", "annually"],
    prices: {
      bdt: { monthly: 299, annually: 2990 },
      usd: { monthly: 9, annually: 90 },
    },
    features: [
      "20 cPanel accounts",
      "40 GB NVMe storage",
      "400 GB bandwidth",
      "Full WHM access",
      "White-label branding",
      "Custom nameservers",
    ],
    resourceSpecs: [
      { label: "cPanel accounts", value: "20" },
      { label: "Storage", value: "40 GB NVMe" },
      { label: "Bandwidth", value: "400 GB" },
      { label: "WHM access", value: "Full" },
      { label: "White-label", value: "Yes" },
      { label: "Custom nameservers", value: "Yes" },
    ],
  },
  {
    id: "reseller-gold",
    category: "reseller",
    name: "Gold",
    tagline: "For growing hosting resellers.",
    popular: true,
    whmcsPid: 32,
    billingCycles: ["monthly", "annually"],
    prices: {
      bdt: { monthly: 599, annually: 5990 },
      usd: { monthly: 18, annually: 180 },
    },
    features: [
      "50 cPanel accounts",
      "100 GB NVMe storage",
      "1 TB bandwidth",
      "Full WHM access",
      "White-label branding",
      "Custom nameservers",
    ],
    resourceSpecs: [
      { label: "cPanel accounts", value: "50" },
      { label: "Storage", value: "100 GB NVMe" },
      { label: "Bandwidth", value: "1 TB" },
      { label: "WHM access", value: "Full" },
      { label: "White-label", value: "Yes" },
      { label: "Custom nameservers", value: "Yes" },
    ],
  },
  {
    id: "reseller-platinum",
    category: "reseller",
    name: "Platinum",
    tagline: "Scale without limits.",
    whmcsPid: 33,
    billingCycles: ["monthly", "annually"],
    prices: {
      bdt: { monthly: 1199, annually: 11990 },
      usd: { monthly: 36, annually: 360 },
    },
    features: [
      "Unlimited cPanel accounts",
      "250 GB NVMe storage",
      "3 TB bandwidth",
      "Full WHM access",
      "White-label branding",
      "Custom nameservers",
    ],
    resourceSpecs: [
      { label: "cPanel accounts", value: "Unlimited" },
      { label: "Storage", value: "250 GB NVMe" },
      { label: "Bandwidth", value: "3 TB" },
      { label: "WHM access", value: "Full" },
      { label: "White-label", value: "Yes" },
      { label: "Custom nameservers", value: "Yes" },
    ],
  },

  /* ---------------------------------- VPS --------------------------------- */
  {
    id: "vps-v1",
    category: "vps",
    name: "V1",
    tagline: "Entry-level VPS for small projects.",
    whmcsPid: 41,
    billingCycles: ["monthly", "quarterly", "annually"],
    prices: {
      bdt: { monthly: 699, quarterly: 1997, annually: 6990 },
      usd: { monthly: 21, quarterly: 60, annually: 210 },
    },
    features: [
      "1 vCPU core",
      "1 GB RAM",
      "20 GB NVMe storage",
      "500 GB bandwidth",
      "1 IPv4 + IPv6",
      "Full root access",
      "DDoS protection",
    ],
    resourceSpecs: [
      { label: "vCPU", value: "1 core" },
      { label: "RAM", value: "1 GB" },
      { label: "Storage", value: "20 GB NVMe" },
      { label: "Bandwidth", value: "500 GB @ 1 Gbps" },
      { label: "IP addresses", value: "1x IPv4 + 1x IPv6" },
      { label: "Root access", value: "Yes" },
    ],
  },
  {
    id: "vps-v2",
    category: "vps",
    name: "V2",
    tagline: "Balanced performance for websites.",
    popular: true,
    whmcsPid: 42,
    billingCycles: ["monthly", "quarterly", "annually"],
    prices: {
      bdt: { monthly: 1299, quarterly: 3699, annually: 12990 },
      usd: { monthly: 39, quarterly: 111, annually: 390 },
    },
    features: [
      "2 vCPU cores",
      "4 GB RAM",
      "60 GB NVMe storage",
      "2 TB bandwidth",
      "1 IPv4 + IPv6",
      "Full root access",
      "DDoS protection",
    ],
    resourceSpecs: [
      { label: "vCPU", value: "2 cores" },
      { label: "RAM", value: "4 GB" },
      { label: "Storage", value: "60 GB NVMe" },
      { label: "Bandwidth", value: "2 TB @ 1 Gbps" },
      { label: "IP addresses", value: "1x IPv4 + 1x IPv6" },
      { label: "Root access", value: "Yes" },
    ],
  },
  {
    id: "vps-v4",
    category: "vps",
    name: "V4",
    tagline: "For resource-hungry applications.",
    whmcsPid: 43,
    billingCycles: ["monthly", "quarterly", "annually"],
    prices: {
      bdt: { monthly: 2599, quarterly: 7399, annually: 25990 },
      usd: { monthly: 78, quarterly: 222, annually: 780 },
    },
    features: [
      "4 vCPU cores",
      "8 GB RAM",
      "120 GB NVMe storage",
      "4 TB bandwidth",
      "2 IPv4 + IPv6",
      "Full root access",
      "DDoS protection",
    ],
    resourceSpecs: [
      { label: "vCPU", value: "4 cores" },
      { label: "RAM", value: "8 GB" },
      { label: "Storage", value: "120 GB NVMe" },
      { label: "Bandwidth", value: "4 TB @ 1 Gbps" },
      { label: "IP addresses", value: "2x IPv4 + IPv6" },
      { label: "Root access", value: "Yes" },
    ],
  },
  {
    id: "vps-v8",
    category: "vps",
    name: "V8",
    tagline: "High-performance for production workloads.",
    whmcsPid: 44,
    billingCycles: ["monthly", "quarterly", "annually"],
    prices: {
      bdt: { monthly: 5199, quarterly: 14799, annually: 51990 },
      usd: { monthly: 156, quarterly: 444, annually: 1560 },
    },
    features: [
      "8 vCPU cores",
      "16 GB RAM",
      "240 GB NVMe storage",
      "8 TB bandwidth",
      "2 IPv4 + IPv6",
      "Full root access",
      "DDoS protection",
    ],
    resourceSpecs: [
      { label: "vCPU", value: "8 cores" },
      { label: "RAM", value: "16 GB" },
      { label: "Storage", value: "240 GB NVMe" },
      { label: "Bandwidth", value: "8 TB @ 1 Gbps" },
      { label: "IP addresses", value: "2x IPv4 + IPv6" },
      { label: "Root access", value: "Yes" },
    ],
  },

  /* ------------------------------ BDIX VPS ------------------------------- */
  {
    id: "bdix-vps-b1",
    category: "bdix-vps",
    name: "B1",
    tagline: "Local VPS for fast BDIX connectivity.",
    whmcsPid: 51,
    billingCycles: ["monthly", "quarterly", "annually"],
    prices: {
      bdt: { monthly: 899, quarterly: 2567, annually: 8990 },
      usd: { monthly: 27, quarterly: 77, annually: 270 },
    },
    features: [
      "1 vCPU core",
      "2 GB RAM",
      "30 GB NVMe storage",
      "1 TB bandwidth",
      "BDIX + international uplink",
      "Full root access",
      "DDoS protection",
    ],
    resourceSpecs: [
      { label: "vCPU", value: "1 core" },
      { label: "RAM", value: "2 GB" },
      { label: "Storage", value: "30 GB NVMe" },
      { label: "Bandwidth", value: "1 TB" },
      { label: "Network", value: "BDIX + Intl @ 1 Gbps" },
      { label: "Root access", value: "Yes" },
    ],
  },
  {
    id: "bdix-vps-b2",
    category: "bdix-vps",
    name: "B2",
    tagline: "Low-latency hosting for BD visitors.",
    popular: true,
    whmcsPid: 52,
    billingCycles: ["monthly", "quarterly", "annually"],
    prices: {
      bdt: { monthly: 1699, quarterly: 4849, annually: 16990 },
      usd: { monthly: 51, quarterly: 145, annually: 510 },
    },
    features: [
      "2 vCPU cores",
      "4 GB RAM",
      "80 GB NVMe storage",
      "3 TB bandwidth",
      "BDIX + international uplink",
      "Full root access",
      "DDoS protection",
    ],
    resourceSpecs: [
      { label: "vCPU", value: "2 cores" },
      { label: "RAM", value: "4 GB" },
      { label: "Storage", value: "80 GB NVMe" },
      { label: "Bandwidth", value: "3 TB" },
      { label: "Network", value: "BDIX + Intl @ 1 Gbps" },
      { label: "Root access", value: "Yes" },
    ],
  },
  {
    id: "bdix-vps-b4",
    category: "bdix-vps",
    name: "B4",
    tagline: "Powerful local VPS for heavy workloads.",
    whmcsPid: 53,
    billingCycles: ["monthly", "quarterly", "annually"],
    prices: {
      bdt: { monthly: 3299, quarterly: 9409, annually: 32990 },
      usd: { monthly: 99, quarterly: 282, annually: 990 },
    },
    features: [
      "4 vCPU cores",
      "8 GB RAM",
      "160 GB NVMe storage",
      "5 TB bandwidth",
      "BDIX + international uplink",
      "Full root access",
      "DDoS protection",
    ],
    resourceSpecs: [
      { label: "vCPU", value: "4 cores" },
      { label: "RAM", value: "8 GB" },
      { label: "Storage", value: "160 GB NVMe" },
      { label: "Bandwidth", value: "5 TB" },
      { label: "Network", value: "BDIX + Intl @ 1 Gbps" },
      { label: "Root access", value: "Yes" },
    ],
  },
];

export const defaultTlds = [
  { tld: ".com", registerBdt: 1090, registerUsd: 11, renewBdt: 1390, renewUsd: 14, transferBdt: 1090, transferUsd: 11, minYears: 1 },
  { tld: ".net", registerBdt: 1190, registerUsd: 12, renewBdt: 1490, renewUsd: 15, transferBdt: 1190, transferUsd: 12, minYears: 1 },
  { tld: ".org", registerBdt: 1190, registerUsd: 12, renewBdt: 1490, renewUsd: 15, transferBdt: 1190, transferUsd: 12, minYears: 1 },
  { tld: ".info", registerBdt: 990, registerUsd: 10, renewBdt: 1290, renewUsd: 13, transferBdt: 990, transferUsd: 10, minYears: 1 },
  { tld: ".xyz", registerBdt: 490, registerUsd: 5, renewBdt: 1090, renewUsd: 11, transferBdt: 490, transferUsd: 5, minYears: 1 },
  { tld: ".online", registerBdt: 1290, registerUsd: 13, renewBdt: 1590, renewUsd: 16, transferBdt: 1290, transferUsd: 13, minYears: 1 },
  { tld: ".store", registerBdt: 1490, registerUsd: 15, renewBdt: 1790, renewUsd: 18, transferBdt: 1490, transferUsd: 15, minYears: 1 },
  { tld: ".bd", registerBdt: 2490, registerUsd: 25, renewBdt: 2490, renewUsd: 25, transferBdt: 2490, transferUsd: 25, premium: true, minYears: 1 },
  { tld: ".com.bd", registerBdt: 1490, registerUsd: 15, renewBdt: 1490, renewUsd: 15, transferBdt: 1490, transferUsd: 15, premium: true, minYears: 1 },
  { tld: ".net.bd", registerBdt: 1490, registerUsd: 15, renewBdt: 1490, renewUsd: 15, transferBdt: 1490, transferUsd: 15, premium: true, minYears: 1 },
  { tld: ".org.bd", registerBdt: 1490, registerUsd: 15, renewBdt: 1490, renewUsd: 15, transferBdt: 1490, transferUsd: 15, premium: true, minYears: 1 },
  { tld: ".tech", registerBdt: 1690, registerUsd: 17, renewBdt: 1990, renewUsd: 20, transferBdt: 1690, transferUsd: 17, minYears: 1 },
  { tld: ".site", registerBdt: 690, registerUsd: 7, renewBdt: 1290, renewUsd: 13, transferBdt: 690, transferUsd: 7, minYears: 1 },
  { tld: ".me", registerBdt: 1890, registerUsd: 19, renewBdt: 2190, renewUsd: 22, transferBdt: 1890, transferUsd: 19, minYears: 1 },
  { tld: ".io", registerBdt: 4490, registerUsd: 45, renewBdt: 4790, renewUsd: 48, transferBdt: 4490, transferUsd: 45, premium: true, minYears: 1 },
  { tld: ".co", registerBdt: 2490, registerUsd: 25, renewBdt: 2790, renewUsd: 28, transferBdt: 2490, transferUsd: 25, minYears: 1 },
] as import("@/lib/site-types").TldConfig[];
